services:
  - type: web
    name: mysite
    plan: free
    env: python
    pythonVersion: 3.12.15

    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      python manage.py migrate --noinput
      gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        sync: false